// populateDB.js

const mongoose = require('mongoose');

// Replace 'your_mongodb_uri' with your actual MongoDB URI
mongoose.connect('mongodb://localhost:27017/youtube_db', { useNewUrlParser: true, useUnifiedTopology: true })
  .then(() => console.log('MongoDB connected...'))
  .catch(err => console.error(err));

const videoSchema = new mongoose.Schema({
  title: String,
  description: String,
  videoUrl: String,
  thumbnailUrl: String,
  duration: String,
  owner: String,
  views: Number,
  id: Number,
  time_publish: Number,
  time_type: String,
  user_icon: String,
  likes: Number,
  comments: [String]
}, { collection: 'videos' });

const Video = mongoose.model('Video', videoSchema);

const videos = [
    {
        id: 1,
        title: 'Video 1',
        description: 'Description 1',
        videoUrl: 'https://www.learningcontainer.com/wp-content/uploads/2020/05/sample-mp4-file.mp4',
        thumbnailUrl: 'thumbnail1.jpg',
        duration: '8:15',
        owner: 'HAIFA MAN',
        views: 721,
        time_publish: 4,
        time_type: 'years',
        user_icon: 'https://yt3.ggpht.com/xqpDLeDfVG5K9w3VDXzQsg_0tvwqKp9Rg1QSc5d1XUfFTgXeHlQuqJ45ErN9qOCkLB2QwE2MnmE=s68-c-k-c0x00ffffff-no-rj',
        likes: 0,
        comments: []
      },
      {
        id: 2,
        title: 'Video 2',
        description: 'Description 2',
        videoUrl: 'https://www.learningcontainer.com/wp-content/uploads/2020/05/sample-mp4-file.mp4',
        thumbnailUrl: 'thumbnail2.jpg',
        duration: '5:45',
        owner: 'TEL AVIV MAN',
        views: 1050,
        time_publish: 1,
        time_type: 'month',
        user_icon: 'https://yt3.ggpht.com/xqpDLeDfVG5K9w3VDXzQsg_0tvwqKp9Rg1QSc5d1XUfFTgXeHlQuqJ45ErN9qOCkLB2QwE2MnmE=s68-c-k-c0x00ffffff-no-rj',
        likes: 0,
        comments: []
      },
      {
        id: 3,
        title: 'Video 3',
        description: 'Description 3',
        videoUrl: 'https://www.learningcontainer.com/wp-content/uploads/2020/05/sample-mp4-file.mp4',
        thumbnailUrl: 'thumbnail3.jpg',
        duration: '12:30',
        owner: 'JERUSALEM MAN',
        views: 302,
        time_publish: 2,
        time_type: 'weeks',
        user_icon: 'https://yt3.ggpht.com/xqpDLeDfVG5K9w3VDXzQsg_0tvwqKp9Rg1QSc5d1XUfFTgXeHlQuqJ45ErN9qOCkLB2QwE2MnmE=s68-c-k-c0x00ffffff-no-rj',
        likes: 0,
        comments: []
      },
      {
        id: 4,
        title: 'Video 4',
        description: 'Description 4',
        videoUrl: 'https://www.learningcontainer.com/wp-content/uploads/2020/05/sample-mp4-file.mp4',
        thumbnailUrl: 'thumbnail4.jpg',
        duration: '3:58',
        owner: 'HAIFA MAN',
        views: 430,
        time_publish: 5,
        time_type: 'days',
        user_icon: 'https://yt3.ggpht.com/xqpDLeDfVG5K9w3VDXzQsg_0tvwqKp9Rg1QSc5d1XUfFTgXeHlQuqJ45ErN9qOCkLB2QwE2MnmE=s68-c-k-c0x00ffffff-no-rj',
        likes: 0,
        comments: []
      },
      {
        id: 5,
        title: 'Video 5',
        description: 'Description 5',
        videoUrl: 'https://www.learningcontainer.com/wp-content/uploads/2020/05/sample-mp4-file.mp4',
        thumbnailUrl: 'thumbnail5.jpg',
        duration: '6:02',
        owner: 'TEL AVIV MAN',
        views: 892,
        time_publish: 3,
        time_type: 'days',
        user_icon: 'https://yt3.ggpht.com/xqpDLeDfVG5K9w3VDXzQsg_0tvwqKp9Rg1QSc5d1XUfFTgXeHlQuqJ45ErN9qOCkLB2QwE2MnmE=s68-c-k-c0x00ffffff-no-rj',
        likes: 0,
        comments: []
      },
      {
        id: 6,
        title: 'Video 6',
        description: 'Description 6',
        videoUrl: 'https://www.learningcontainer.com/wp-content/uploads/2020/05/sample-mp4-file.mp4',
        thumbnailUrl: 'thumbnail6.jpg',
        duration: '9:20',
        owner: 'JERUSALEM MAN',
        views: 125,
        time_publish: 1,
        time_type: 'week',
        user_icon: 'https://yt3.ggpht.com/xqpDLeDfVG5K9w3VDXzQsg_0tvwqKp9Rg1QSc5d1XUfFTgXeHlQuqJ45ErN9qOCkLB2QwE2MnmE=s68-c-k-c0x00ffffff-no-rj',
        likes: 0,
        comments: []
      },
      {
        id: 7,
        title: 'Video 7',
        description: 'Description 7',
        videoUrl: 'https://www.learningcontainer.com/wp-content/uploads/2020/05/sample-mp4-file.mp4',
        thumbnailUrl: 'thumbnail7.jpg',
        duration: '4:45',
        owner: 'HAIFA MAN',
        views: 510,
        time_publish: 3,
        time_type: 'months',
        user_icon: 'https://yt3.ggpht.com/xqpDLeDfVG5K9w3VDXzQsg_0tvwqKp9Rg1QSc5d1XUfFTgXeHlQuqJ45ErN9qOCkLB2QwE2MnmE=s68-c-k-c0x00ffffff-no-rj',
        likes: 0,
        comments: []
      },
      {
        id: 8,
        title: 'Video 8',
        description: 'Description 8',
        videoUrl: 'https://www.learningcontainer.com/wp-content/uploads/2020/05/sample-mp4-file.mp4',
        thumbnailUrl: 'thumbnail8.jpg',
        duration: '7:10',
        owner: 'TEL AVIV MAN',
        views: 392,
        time_publish: 2,
        time_type: 'days',
        user_icon: 'https://yt3.ggpht.com/xqpDLeDfVG5K9w3VDXzQsg_0tvwqKp9Rg1QSc5d1XUfFTgXeHlQuqJ45ErN9qOCkLB2QwE2MnmE=s68-c-k-c0x00ffffff-no-rj',
        likes: 0,
        comments: []
      },
      {
        id: 9,
        title: 'Video 9',
        description: 'Description 9',
        videoUrl: 'https://www.learningcontainer.com/wp-content/uploads/2020/05/sample-mp4-file.mp4',
        thumbnailUrl: 'thumbnail9.jpg',
        duration: '5:55',
        owner: 'JERUSALEM MAN',
        views: 842,
        time_publish: 1,
        time_type: 'day',
        user_icon: 'https://yt3.ggpht.com/xqpDLeDfVG5K9w3VDXzQsg_0tvwqKp9Rg1QSc5d1XUfFTgXeHlQuqJ45ErN9qOCkLB2QwE2MnmE=s68-c-k-c0x00ffffff-no-rj',
        likes: 0,
        comments: []
      },
      {
        id: 10,
        title: 'Video 10',
        description: 'Description 10',
        videoUrl: 'https://www.learningcontainer.com/wp-content/uploads/2020/05/sample-mp4-file.mp4',
        thumbnailUrl: 'thumbnail10.jpg',
        duration: '2:45',
        owner: 'JERUSALEM MAN',
        views: 242,
        time_publish: 3,
        time_type: 'years',
        user_icon: 'https://yt3.ggpht.com/xqpDLeDfVG5K9w3VDXzQsg_0tvwqKp9Rg1QSc5d1XUfFTgXeHlQuqJ45ErN9qOCkLB2QwE2MnmE=s68-c-k-c0x00ffffff-no-rj',
        likes: 10,
        comments: []
      },
      {
        id: 11,
        title: 'Climbing Mount Everest',
        description: 'Join us on an epic journey to climb the tallest mountain on Earth.',
        videoUrl: 'https://www.learningcontainer.com/wp-content/uploads/2020/05/sample-mp4-file.mp4',
        thumbnailUrl: 'thumbnail11.jpg',
        duration: '12:45',
        owner: 'Adventure Seeker',
        views: 1200,
        time_publish: 1,
        time_type: 'year',
        user_icon: 'https://example.com/user11.jpg',
        likes: 350,
        comments: []
      },
      {
        id: 12,
        title: 'Cooking Masterclass: Pasta Carbonara',
        description: 'Learn how to make the perfect Pasta Carbonara from an Italian chef.',
        videoUrl: 'https://www.learningcontainer.com/wp-content/uploads/2020/05/sample-mp4-file.mp4',
        thumbnailUrl: 'thumbnail12.jpg',
        duration: '6:30',
        owner: 'Chef Giovanni',
        views: 580,
        time_publish: 6,
        time_type: 'months',
        user_icon: 'https://example.com/user12.jpg',
        likes: 150,
        comments: []
      },
      {
        id: 13,
        title: 'Exploring Ancient Ruins in Greece',
        description: 'Discover the mysteries of ancient Greek civilizations as we explore their ruins.',
        videoUrl: 'https://www.learningcontainer.com/wp-content/uploads/2020/05/sample-mp4-file.mp4',
        thumbnailUrl: 'thumbnail13.jpg',
        duration: '9:20',
        owner: 'History Buff',
        views: 920,
        time_publish: 2,
        time_type: 'years',
        user_icon: 'https://example.com/user13.jpg',
        likes: 280,
        comments: []
      },
      {
        id: 14,
        title: 'Painting a Starry Night',
        description: 'Watch an artist recreate Vincent van Gogh\'s masterpiece in real time.',
        videoUrl: 'https://www.learningcontainer.com/wp-content/uploads/2020/05/sample-mp4-file.mp4',
        thumbnailUrl: 'thumbnail14.jpg',
        duration: '15:00',
        owner: 'Art Enthusiast',
        views: 1450,
        time_publish: 3,
        time_type: 'years',
        user_icon: 'https://example.com/user14.jpg',
        likes: 480,
        comments: []
      },
      {
        id: 15,
        title: 'Cross-Country Road Trip',
        description: 'Embark on a road trip across the country, exploring hidden gems and local culture.',
        videoUrl: 'https://www.learningcontainer.com/wp-content/uploads/2020/05/sample-mp4-file.mp4',
        thumbnailUrl: 'thumbnail15.jpg',
        duration: '18:30',
        owner: 'Wanderlust Traveler',
        views: 2300,
        time_publish: 4,
        time_type: 'years',
        user_icon: 'https://example.com/user15.jpg',
        likes: 600,
        comments: []
      },
      {
        id: 16,
        title: 'Gardening Tips for Beginners',
        description: 'Learn essential gardening tips and tricks to start your own garden at home.',
        videoUrl: 'https://www.learningcontainer.com/wp-content/uploads/2020/05/sample-mp4-file.mp4',
        thumbnailUrl: 'thumbnail16.jpg',
        duration: '7:55',
        owner: 'Green Thumb',
        views: 780,
        time_publish: 1,
        time_type: 'year',
        user_icon: 'https://example.com/user16.jpg',
        likes: 200,
        comments: []
      },
      {
        id: 17,
        title: 'Photography Masterclass: Capturing the Northern Lights',
        description: 'Join a professional photographer as they capture the mesmerizing Northern Lights.',
        videoUrl: 'https://www.learningcontainer.com/wp-content/uploads/2020/05/sample-mp4-file.mp4',
        thumbnailUrl: 'thumbnail17.jpg',
        duration: '11:10',
        owner: 'Nature Photographer',
        views: 980,
        time_publish: 8,
        time_type: 'months',
        user_icon: 'https://example.com/user17.jpg',
        likes: 380,
        comments: []
      },
      {
        id: 18,
        title: 'Cooking Challenge: 5-Minute Desserts',
        description: 'Take on the challenge of making delicious desserts in just 5 minutes.',
        videoUrl: 'https://www.learningcontainer.com/wp-content/uploads/2020/05/sample-mp4-file.mp4',
        thumbnailUrl: 'thumbnail18.jpg',
        duration: '5:00',
        owner: 'Dessert Lover',
        views: 510,
        time_publish: 10,
        time_type: 'months',
        user_icon: 'https://example.com/user18.jpg',
        likes: 120,
        comments: []
      },
      {
        id: 19,
        title: 'Virtual Tour: Tokyo, Japan',
        description: 'Explore the vibrant streets of Tokyo and its unique blend of tradition and modernity.',
        videoUrl: 'https://www.learningcontainer.com/wp-content/uploads/2020/05/sample-mp4-file.mp4',
        thumbnailUrl: 'thumbnail19.jpg',
        duration: '14:20',
        owner: 'Travel Enthusiast',
        views: 1750,
        time_publish: 2,
        time_type: 'years',
        user_icon: 'https://example.com/user19.jpg',
        likes: 420,
        comments: []
      },
      {
        id: 20,
        title: 'Fitness Challenge: 30-Day Yoga Journey',
        description: 'Embark on a transformative 30-day yoga journey to improve flexibility and inner peace.',
        videoUrl: 'https://www.learningcontainer.com/wp-content/uploads/2020/05/sample-mp4-file.mp4',
        thumbnailUrl: 'thumbnail20.jpg',
        duration: '30:00',
        owner: 'Yoga Instructor',
        views: 3100,
        time_publish: 1,
        time_type: 'year',
        user_icon: 'https://example.com/user20.jpg',
        likes: 900,
        comments: []
      },
      {
        id: 21,
        title: 'Hiking the Grand Canyon',
        description: 'Experience the breathtaking views and challenges of hiking the Grand Canyon.',
        videoUrl: 'https://www.learningcontainer.com/wp-content/uploads/2020/05/sample-mp4-file.mp4',
        thumbnailUrl: 'thumbnail21.jpg',
        duration: '10:25',
        owner: 'Nature Explorer',
        views: 1100,
        time_publish: 2,
        time_type: 'years',
        user_icon: 'https://example.com/user21.jpg',
        likes: 300,
        comments: []
      },
      {
        id: 22,
        title: 'Baking Artisan Bread from Scratch',
        description: 'Learn the art of baking delicious artisan bread right in your own kitchen.',
        videoUrl: 'https://www.learningcontainer.com/wp-content/uploads/2020/05/sample-mp4-file.mp4',
        thumbnailUrl: 'thumbnail22.jpg',
        duration: '8:45',
        owner: 'Bread Enthusiast',
        views: 890,
        time_publish: 1,
        time_type: 'year',
        user_icon: 'https://example.com/user22.jpg',
        likes: 250,
        comments: []
      },
      {
        id: 23,
        title: 'Discovering Underwater Worlds',
        description: 'Dive into the mysteries of underwater ecosystems and marine life around the world.',
        videoUrl: 'https://www.learningcontainer.com/wp-content/uploads/2020/05/sample-mp4-file.mp4',
        thumbnailUrl: 'thumbnail23.jpg',
        duration: '15:30',
        owner: 'Ocean Explorer',
        views: 1550,
        time_publish: 3,
        time_type: 'years',
        user_icon: 'https://example.com/user23.jpg',
        likes: 400,
        comments: []
      },
      {
        id: 24,
        title: 'Sketching Landscapes with Charcoal',
        description: 'Join an artist as they demonstrate techniques for sketching landscapes using charcoal.',
        videoUrl: 'https://www.learningcontainer.com/wp-content/uploads/2020/05/sample-mp4-file.mp4',
        thumbnailUrl: 'thumbnail24.jpg',
        duration: '12:15',
        owner: 'Art Sketcher',
        views: 1250,
        time_publish: 2,
        time_type: 'years',
        user_icon: 'https://example.com/user24.jpg',
        likes: 350,
        comments: []
      },
      {
        id: 25,
        title: 'Road Cycling through the Alps',
        description: 'Embark on a thrilling road cycling adventure through the stunning Alps mountains.',
        videoUrl: 'https://www.learningcontainer.com/wp-content/uploads/2020/05/sample-mp4-file.mp4',
        thumbnailUrl: 'thumbnail25.jpg',
        duration: '20:00',
        owner: 'Cycling Enthusiast',
        views: 2100,
        time_publish: 4,
        time_type: 'years',
        user_icon: 'https://example.com/user25.jpg',
        likes: 600,
        comments: []
      },
      {
        id: 26,
        title: 'Urban Gardening in Small Spaces',
        description: 'Learn innovative techniques for gardening in small urban spaces and apartments.',
        videoUrl: 'https://www.learningcontainer.com/wp-content/uploads/2020/05/sample-mp4-file.mp4',
        thumbnailUrl: 'thumbnail26.jpg',
        duration: '9:10',
        owner: 'Urban Gardener',
        views: 980,
        time_publish: 1,
        time_type: 'year',
        user_icon: 'https://example.com/user26.jpg',
        likes: 280,
        comments: []
      },
      {
        id: 27,
                title: 'Photography Masterclass: Capturing Wildlife',
        description: 'Join a wildlife photographer as they capture stunning images of animals in their natural habitat.',
        videoUrl: 'https://www.learningcontainer.com/wp-content/uploads/2020/05/sample-mp4-file.mp4',
        thumbnailUrl: 'thumbnail27.jpg',
        duration: '13:20',
        owner: 'Wildlife Photographer',
        views: 1350,
        time_publish: 3,
        time_type: 'years',
        user_icon: 'https://example.com/user27.jpg',
        likes: 420,
        comments: []
      },
      {
        id: 28,
        title: 'Gourmet Cooking: French Cuisine',
        description: 'Explore the art of French cuisine and learn to cook gourmet dishes like a professional chef.',
        videoUrl: 'https://www.learningcontainer.com/wp-content/uploads/2020/05/sample-mp4-file.mp4',
        thumbnailUrl: 'thumbnail28.jpg',
        duration: '11:45',
        owner: 'Chef Pierre',
        views: 1150,
        time_publish: 2,
        time_type: 'years',
        user_icon: 'https://example.com/user28.jpg',
        likes: 380,
        comments: []
      },
      {
        id: 29,
        title: 'Virtual Tour: Paris, France',
        description: 'Take a virtual tour of the romantic city of Paris, exploring its iconic landmarks and rich history.',
        videoUrl: 'https://www.learningcontainer.com/wp-content/uploads/2020/05/sample-mp4-file.mp4',
        thumbnailUrl: 'thumbnail29.jpg',
        duration: '16:30',
        owner: 'Travel Enthusiast',
        views: 1650,
        time_publish: 4,
        time_type: 'years',
        user_icon: 'https://example.com/user29.jpg',
        likes: 480,
        comments: []
      },
      {
        id: 30,
        title: 'Strength Training: Full Body Workout',
        description: 'Get stronger with this full-body strength training workout designed to build muscle and endurance.',
        videoUrl: 'https://www.learningcontainer.com/wp-content/uploads/2020/05/sample-mp4-file.mp4',
        thumbnailUrl: 'thumbnail30.jpg',
        duration: '25:00',
        owner: 'Fitness Trainer',
        views: 2800,
        time_publish: 1,
        time_type: 'year',
        user_icon: 'https://example.com/user30.jpg',
        likes: 750,
        comments: []
      }

  // Add more video objects as needed
];

Video.insertMany(videos)
  .then(() => {
    console.log('Data inserted');
    mongoose.connection.close();
  })
  .catch(err => {
    console.error(err);
    mongoose.connection.close();
  });
